[package]
name = "hw1"
version = "1.0.0"
authors = ["Anthony Morrell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
